### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ShaneOss**
bump gluonts version. Previous version use old version of pydantic.

### CODE REVIEW

**Comment by kashif** [comment]
@ShaneOss thanks mate! I was thinking of upgrading to lighting instead of pytorch-lightning... what do you think?

**Comment by ShaneOss** [comment]
Hey @kashif , good idea. It works, no issues.
Also fixes a few legacy dependency problems.

**Comment by ashok-arjun** [comment]
Thanks @ShaneOss. I'd have to check if this causes any problems when training, since we found our version of GluonTS to be the most stable one. Will check it soon.

Regarding lightning, @kashif, that'll require a good amount of refactoring if you want to upgrade: are there any benefits?

**Comment by kashif** [comment]
@ShaneOss  so we realized that if we require `gluonts[torch]` as the top level requirement, it pulls in the working versions of lighting and pytorch-lightning so closing this PR for now

**Pull request closed without merging**
